# Generated by Django 5.1.2 on 2024-10-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingapp', '0002_launchregistrants_referercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchregistrants',
            name='referercode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
