# Generated by Django 5.1.2 on 2024-10-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingapp', '0003_alter_launchregistrants_referercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchregistrants',
            name='numberOfReferrals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
