# Generated by Django 5.1.2 on 2024-10-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingapp', '0004_launchregistrants_numberofreferrals'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=1000)),
                ('numberOfReferrals', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='launchregistrants',
            name='numberOfReferrals',
        ),
    ]
